ci:
  skip:
    - mypy

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.8.2"
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@latest
          - prettier-plugin-toml@latest
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
  - repo: local
    hooks:
      - id: mypy
        name: static type check
        language: system
        entry: .venv/bin/mypy --fast-module-lookup
        pass_filenames: false
