name: Run tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: ["windows-latest", "ubuntu-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: true
      - name: Install dependencies
        run: pdm install --frozen-lock
      - name: Run pytest
        run: pdm run pytest --cov=flay --cov-report=lcov:coverage/.coverage.${{ runner.os }}-${{ matrix.python-version }}
      - name: Store coverage files
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{runner.os}}-${{ matrix.python-version }}
          path: coverage
          include-hidden-files: true

  coverage-combine:
    runs-on: ubuntu-latest
    name: Combine coverage
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
      - name: Download coverage files
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          path: coverage
          merge-multiple: true
      - run: coverage combine coverage
      - run: coverage html --title "Coverage for ${{ github.sha }}"
      - name: Store coverage HTML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov
          include-hidden-files: true
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
